version: "3"

vars:
  BINARY_NAME: rss-telegram-feed
  GO_VERSION: 1.22

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  deps:
    desc: Download and install dependencies
    cmds:
      - go mod download
      - go mod tidy

  generate:
    desc: Generate code (enums, etc.)
    cmds:
      - "go generate -x ./..."

  go:generate:
    desc: Run go generate (alias for generate)
    cmds:
      - task: generate

  build:
    desc: Build the application
    deps: [generate]
    cmds:
      - go build -o {{.BINARY_NAME}} .
    generates:
      - "{{.BINARY_NAME}}"

  run:
    desc: Run the application locally
    deps: [deps]
    cmds:
      - go run .

  run:local:
    desc: Run the application with local config.yaml
    deps: [deps]
    env:
      APP_ENV: local
    cmds:
      - go run .

  test:
    desc: Run tests
    deps: [deps]
    cmds:
      - go test -v ./...

  test:coverage:
    desc: Run tests with coverage
    deps: [deps]
    cmds:
      - go test -v -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html

  lint:
    desc: Run linter
    deps: [deps]
    cmds:
      - golangci-lint run || echo "golangci-lint not installed, skipping..."

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f {{.BINARY_NAME}}
      - rm -rf ./data
      - rm -f coverage.out coverage.html

  setup:
    desc: Initial setup for local development
    cmds:
      - |
        if [ ! -f config.yaml ] && [ ! -f config.yml ] && [ ! -f config.json ] && [ ! -f config.toml ]; then
          cp config.example.yaml config.yaml
          echo "Created config.yaml from template. Please edit it with your values."
          echo "You can also use config.json or config.toml instead."
        else
          echo "Config file already exists."
        fi
      - task: deps

  tilt:up:
    desc: Start Tilt for local development
    cmds:
      - tilt up

  tilt:down:
    desc: Stop Tilt
    cmds:
      - tilt down

  tilt:logs:
    desc: Show Tilt logs
    cmds:
      - tilt logs

  dev:
    desc: Start development environment with Tilt
    cmds:
      - task: tilt:up
